// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct StartRequest {
  var path: String
  var outputWidth: Int64
  var outputHeight: Int64
  var frameRate: Double
  var bitrate: Int64
  var iFrameInterval: Int64

  static func fromList(_ list: [Any?]) -> StartRequest? {
    let path = list[0] as! String
    let outputWidth = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let outputHeight = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let frameRate = list[3] as! Double
    let bitrate = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let iFrameInterval = list[5] is Int64 ? list[5] as! Int64 : Int64(list[5] as! Int32)

    return StartRequest(
      path: path,
      outputWidth: outputWidth,
      outputHeight: outputHeight,
      frameRate: frameRate,
      bitrate: bitrate,
      iFrameInterval: iFrameInterval
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      outputWidth,
      outputHeight,
      frameRate,
      bitrate,
      iFrameInterval,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LogArg {
  var tag: String? = nil
  var message: String? = nil
  var throwable: String? = nil
  var time: String? = nil

  static func fromList(_ list: [Any?]) -> LogArg? {
    let tag: String? = nilOrValue(list[0])
    let message: String? = nilOrValue(list[1])
    let throwable: String? = nilOrValue(list[2])
    let time: String? = nilOrValue(list[3])

    return LogArg(
      tag: tag,
      message: message,
      throwable: throwable,
      time: time
    )
  }
  func toList() -> [Any?] {
    return [
      tag,
      message,
      throwable,
      time,
    ]
  }
}

private class FastScreenRecorderHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return StartRequest.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class FastScreenRecorderHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? StartRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FastScreenRecorderHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FastScreenRecorderHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FastScreenRecorderHostApiCodecWriter(data: data)
  }
}

class FastScreenRecorderHostApiCodec: FlutterStandardMessageCodec {
  static let shared = FastScreenRecorderHostApiCodec(readerWriter: FastScreenRecorderHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FastScreenRecorderHostApi {
  func start(request: StartRequest) throws
  func capture(completion: @escaping (Result<Void, Error>) -> Void)
  func stop() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FastScreenRecorderHostApiSetup {
  /// The codec used by FastScreenRecorderHostApi.
  static var codec: FlutterStandardMessageCodec { FastScreenRecorderHostApiCodec.shared }
  /// Sets up an instance of `FastScreenRecorderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FastScreenRecorderHostApi?) {
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.FastScreenRecorderHostApi.start", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StartRequest
        do {
          try api.start(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let captureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.FastScreenRecorderHostApi.capture", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      captureChannel.setMessageHandler { _, reply in
        api.capture() { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      captureChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.FastScreenRecorderHostApi.stop", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
  }
}
private class FastScreenRecorderFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return LogArg.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class FastScreenRecorderFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LogArg {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FastScreenRecorderFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FastScreenRecorderFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FastScreenRecorderFlutterApiCodecWriter(data: data)
  }
}

class FastScreenRecorderFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = FastScreenRecorderFlutterApiCodec(readerWriter: FastScreenRecorderFlutterApiCodecReaderWriter())
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class FastScreenRecorderFlutterApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return FastScreenRecorderFlutterApiCodec.shared
  }
  func log(arg argArg: LogArg, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.FastScreenRecorderFlutterApi.log", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([argArg] as [Any?]) { _ in
      completion()
    }
  }
}
