// ignore_for_file: avoid-non-null-assertion, prefer_constructors_over_static_methods, unused_field, combinators_ordering
// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class StartRequest {
  StartRequest({
    required this.path,
    required this.outputWidth,
    required this.outputHeight,
    required this.frameRate,
    required this.bitrate,
    required this.iFrameInterval,
  });

  String path;

  int outputWidth;

  int outputHeight;

  double frameRate;

  int bitrate;

  int iFrameInterval;

  Object encode() {
    return <Object?>[
      path,
      outputWidth,
      outputHeight,
      frameRate,
      bitrate,
      iFrameInterval,
    ];
  }

  static StartRequest decode(Object result) {
    result as List<Object?>;
    return StartRequest(
      path: result[0]! as String,
      outputWidth: result[1]! as int,
      outputHeight: result[2]! as int,
      frameRate: result[3]! as double,
      bitrate: result[4]! as int,
      iFrameInterval: result[5]! as int,
    );
  }
}

class CaptureResponse {
  CaptureResponse({
    required this.succeedOrSkipped,
  });

  bool succeedOrSkipped;

  Object encode() {
    return <Object?>[
      succeedOrSkipped,
    ];
  }

  static CaptureResponse decode(Object result) {
    result as List<Object?>;
    return CaptureResponse(
      succeedOrSkipped: result[0]! as bool,
    );
  }
}

class LogArg {
  LogArg({
    this.tag,
    this.message,
    this.throwable,
    this.time,
  });

  String? tag;

  String? message;

  String? throwable;

  String? time;

  Object encode() {
    return <Object?>[
      tag,
      message,
      throwable,
      time,
    ];
  }

  static LogArg decode(Object result) {
    result as List<Object?>;
    return LogArg(
      tag: result[0] as String?,
      message: result[1] as String?,
      throwable: result[2] as String?,
      time: result[3] as String?,
    );
  }
}

class _FastScreenRecorderHostApiCodec extends StandardMessageCodec {
  const _FastScreenRecorderHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CaptureResponse) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is StartRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CaptureResponse.decode(readValue(buffer)!);
      case 129: 
        return StartRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FastScreenRecorderHostApi {
  /// Constructor for [FastScreenRecorderHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FastScreenRecorderHostApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _FastScreenRecorderHostApiCodec();

  Future<void> start(StartRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FastScreenRecorderHostApi.start', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<CaptureResponse> capture() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FastScreenRecorderHostApi.capture', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as CaptureResponse?)!;
    }
  }

  Future<void> stop() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.FastScreenRecorderHostApi.stop', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _FastScreenRecorderFlutterApiCodec extends StandardMessageCodec {
  const _FastScreenRecorderFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is LogArg) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return LogArg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FastScreenRecorderFlutterApi {
  static const MessageCodec<Object?> codec = _FastScreenRecorderFlutterApiCodec();

  void log(LogArg arg);

  static void setup(FastScreenRecorderFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FastScreenRecorderFlutterApi.log', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FastScreenRecorderFlutterApi.log was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final LogArg? arg_arg = (args[0] as LogArg?);
          assert(arg_arg != null,
              'Argument for dev.flutter.pigeon.FastScreenRecorderFlutterApi.log was null, expected non-null LogArg.');
          api.log(arg_arg!);
          return;
        });
      }
    }
  }
}
